apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-recommender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fashion-recommender
  template:
    metadata:
      labels:
        app: fashion-recommender
    spec:
      containers:
      - name: fashion-recommender
        image: sxnjxy404/fashion-recommender:latest

        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: fashion-recommender-service
spec:
  type: NodePort
  selector:
    app: fashion-recommender
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30007
